"""RetroStudio platform-neutral core API."""

from .animation import AnimationClip, AnimationFrame, load_clip, save_clip
from .animation_state import (
    CONDITION_OPERATORS,
    AnimationCondition,
    AnimationState,
    AnimationStateMachine,
    AnimationTransition,
    load_state_machine,
    save_state_machine,
)
from .assets import (
    ASSET_KINDS,
    Asset,
    ContentCache,
    ConversionRequest,
    ResourceUsage,
    budget_diagnostics,
    hash_bytes,
    hash_file,
)
from .behaviours import (
    BEHAVIOUR_TYPES,
    BehaviourDefinition,
    add_behaviour,
    behaviour_type,
    entity_behaviours,
    remove_behaviour,
)
from .collision import (
    COLLIDER_COMPONENT,
    SHAPE_TYPES,
    TRIGGER_COMPONENT,
    CollisionShape,
    collision_diagnostics,
    set_collider,
    set_trigger,
)
from .collision_editor import (
    CollisionOverlay,
    apply_box_collider,
    apply_box_trigger,
    apply_circle_collider,
    overlays_for_entity,
    remove_collision,
)
from .model import Component, Diagnostic, Entity, Project, Scene, load_project, save_project
from .preview import (
    PreviewFact,
    QualityReport,
    TargetPreview,
    build_quality_report,
    guidance_for_diagnostic,
    usage_percent,
)
from .target import (
    TARGET_API_VERSION,
    BackendDescriptor,
    BackendResult,
    BuildArtifact,
    Capability,
    TargetBackend,
    load_backend,
    negotiate_backend,
)
from .workspace import (
    WORKSPACES,
    CommandHistory,
    CreatorGuidance,
    EditorCommand,
    Selection,
    SetTargetCommand,
    WorkspaceState,
)

__all__ = [
    "ASSET_KINDS",
    "AnimationClip",
    "AnimationCondition",
    "AnimationFrame",
    "AnimationState",
    "AnimationStateMachine",
    "AnimationTransition",
    "Asset",
    "BEHAVIOUR_TYPES",
    "BackendDescriptor",
    "BackendResult",
    "BehaviourDefinition",
    "BuildArtifact",
    "COLLIDER_COMPONENT",
    "CONDITION_OPERATORS",
    "Capability",
    "CollisionOverlay",
    "CollisionShape",
    "CommandHistory",
    "Component",
    "ContentCache",
    "ConversionRequest",
    "CreatorGuidance",
    "Diagnostic",
    "EditorCommand",
    "Entity",
    "PreviewFact",
    "Project",
    "QualityReport",
    "ResourceUsage",
    "SHAPE_TYPES",
    "Scene",
    "Selection",
    "SetTargetCommand",
    "TARGET_API_VERSION",
    "TRIGGER_COMPONENT",
    "TargetBackend",
    "TargetPreview",
    "WORKSPACES",
    "WorkspaceState",
    "add_behaviour",
    "apply_box_collider",
    "apply_box_trigger",
    "apply_circle_collider",
    "behaviour_type",
    "budget_diagnostics",
    "build_quality_report",
    "collision_diagnostics",
    "entity_behaviours",
    "guidance_for_diagnostic",
    "hash_bytes",
    "hash_file",
    "load_backend",
    "load_clip",
    "load_project",
    "load_state_machine",
    "negotiate_backend",
    "overlays_for_entity",
    "remove_behaviour",
    "remove_collision",
    "save_clip",
    "save_project",
    "save_state_machine",
    "set_collider",
    "set_trigger",
    "usage_percent",
]
