"""RetroStudio platform-neutral core API."""

from .animation import AnimationClip, AnimationFrame, load_clip, save_clip
from .assets import (
    ASSET_KINDS,
    Asset,
    ContentCache,
    ConversionRequest,
    ResourceUsage,
    budget_diagnostics,
    hash_bytes,
    hash_file,
)
from .model import Component, Diagnostic, Entity, Project, Scene, load_project, save_project
from .preview import (
    PreviewFact,
    QualityReport,
    TargetPreview,
    build_quality_report,
    guidance_for_diagnostic,
    usage_percent,
)
from .target import (
    TARGET_API_VERSION,
    BackendDescriptor,
    BackendResult,
    BuildArtifact,
    Capability,
    TargetBackend,
    load_backend,
    negotiate_backend,
)
from .workspace import (
    WORKSPACES,
    CommandHistory,
    CreatorGuidance,
    EditorCommand,
    Selection,
    SetTargetCommand,
    WorkspaceState,
)

__all__ = [
    "ASSET_KINDS",
    "AnimationClip",
    "AnimationFrame",
    "Asset",
    "BackendDescriptor",
    "BackendResult",
    "BuildArtifact",
    "Capability",
    "CommandHistory",
    "Component",
    "ContentCache",
    "ConversionRequest",
    "CreatorGuidance",
    "Diagnostic",
    "EditorCommand",
    "Entity",
    "PreviewFact",
    "Project",
    "QualityReport",
    "ResourceUsage",
    "Scene",
    "Selection",
    "SetTargetCommand",
    "TARGET_API_VERSION",
    "TargetBackend",
    "TargetPreview",
    "WORKSPACES",
    "WorkspaceState",
    "budget_diagnostics",
    "build_quality_report",
    "guidance_for_diagnostic",
    "hash_bytes",
    "hash_file",
    "load_backend",
    "load_clip",
    "load_project",
    "negotiate_backend",
    "save_clip",
    "save_project",
    "usage_percent",
]
